server:
  remoteWrite:
    - url: http://mimir-distributor.apo-mimir.svc.cluster.local:8080/api/v1/push
      headers:
          "X-Scope-OrgID": "apo"
  persistentVolume:
    enabled: false
  securityContext:
    runAsUser: null
    runAsNonRoot: null
    runAsGroup: null
    fsGroup: null
alertmanager:
  enabled: true
  securityContext:
    runAsUser: null
    runAsNonRoot: null
    runAsGroup: null
    fsGroup: null
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: true
  securityContext:
    runAsUser: null
    runAsNonRoot: null
    runAsGroup: null
    fsGroup: null